[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools>=65.6.3",
    "wheel>=0.38.4",
]

[project]
name = "selcuk_serverless_aws_lambda_sdk"
version = "0.0.2"
description = "Serverless  AWS Lambda SDK for Python"
authors = [{ name = "selcuk_" }]
requires-python = ">=3.7"
dependencies = [
    "selcuk_serverless_sdk",
    "selcuk_serverless_sdk_schema",
    "strenum>=0.4.9",
    "typing-extensions>=4.4", # included in Python 3.8 - 3.11
]
[project.optional-dependencies]
tests = [
    "black>=22.12",
    "pytest>=7.2",
    "ruff>=0.0.199",
]


[tool.ruff]
ignore = ["F401"]
#fix = true
