[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools>=65.6.3",
    "wheel",
]

[project]
name = "serverless-sdk-schema"
version = "0.2.0"
description = "The protobuf generated Serverless SDK Schema"
readme = "README.md"
authors = [{ name = "serverlessinc" }]
requires-python = ">=3.7"
dependencies = [
    "protobuf>=4.22",
    "typing-extensions>=4.4", # included in Python 3.8 - 3.11
]
[project.optional-dependencies]
tests = [
    "black>=22.12",
    "pytest>=7.2",
    "ruff>=0.0.199",
]
[project.urls]
changelog = "https://github.com/serverless/console/blob/main/python/packages/sdk-schema/CHANGELOG.md"
documentation = "https://github.com/serverless/console/tree/main/python/packages/sdk-schema"
homepage = "https://www.serverless.com/console"
repository = "https://github.com/serverless/console"

[tool.ruff]
ignore = ["F401"]
